on:
  push:
    branches:
      - master
    tags:
      - foo.*
      - bar.*

jobs:
  one:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump environment variables
        run: env | sort
      - name: Dump GITHUB & RUNNER environment variables
        run: env | egrep '^(GITHUB|RUNNER)_' | sort
      - name: Confirm shell
        run: echo '$0:' $0
      - name: Extract string from GitHub tag ref e.g. 'refs/tags/foo.0.0.2' -> 'foo'
        run: tag=${GITHUB_REF/*tags\//}; echo 'tag:' ${tag/.*/}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
