on:
  push:
    tags:
      - '*@foo.somewhere'
      - '*@foo.random'
      - '*@bar.somewhere'
      - '*@bar.odd'

# env:
#   TERRAFORM_VERSION: '0.12.18'

jobs:
  one:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: marocchino/setup-terraform@v1.0.1
        with:
          version: 0.12.18
      - name: Verify Terraform version
        run: terraform -version
      - name: Script for string from Git tag ref
        run: echo 'GITHUB_REF:' $GITHUB_REF ; echo 'Extracted string:' $(./scripts/name_from_tagref.sh)
      - name: (Don't) run script with argument derived from tag
        run: echo ./scripts/cat.sh $(./scripts/name_from_tagref.sh).env
      - name: Set app.terraform.io token
        run: |
          echo 'credentials "app.terraform.io" { token = "" }' > ~/.terraformrc
          cat ~/.terraformrc
      - name: Apply Terraform
        env:
          TF_IN_AUTOMATION: true
          TF_CLI_ARGS_apply: -auto-approve
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd terraform && terraform init -reconfigure && terraform apply
